# Mendefinisikan Kubernetes Secret untuk data sensitif MongoDB
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_ROOT_USERNAME: YWRtaW4=  # base64 dari username (contoh: admin)
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==  # base64 dari password (contoh: supersecretpassword)
